# Generated by Django 4.1.5 on 2023-01-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('salary', models.CharField(max_length=250, verbose_name='Зарплата')),
                ('region', models.TextField(verbose_name='Регион')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
