# Generated by Django 4.1.5 on 2023-01-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0002_rename_name_articles_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='names',
            new_name='name',
        ),
    ]
