# Generated by Django 4.1.5 on 2023-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0003_rename_names_articles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='salary',
            field=models.CharField(max_length=80, verbose_name='Зарплата'),
        ),
    ]
