# Generated by Django 4.1.5 on 2023-01-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mainskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('name', models.CharField(max_length=200, verbose_name='Навык')),
                ('count', models.CharField(max_length=50, verbose_name='Количество упоминаний')),
            ],
        ),
    ]
